kernel.config:
    charset:       UTF-8
    error_handler: null

web.config:
    router:       { resource: "%kernel.root_dir%/config/routing.yml" }
    validation:   { enabled: true, annotations: true }

web.templating:
    escaping:     htmlspecialchars

news.planet:
    url:          http://pipes.yahoo.com/pipes/pipe.run?_id=fKxxZiQZ3hGaIgbtdfQQIA&_render=rss

news.twitter:
    url:          http://search.twitter.com/search.rss
    search_query: "#symfony"

news.slideshare:
    url:          http://www.slideshare.net/api/2/get_slideshows_by_tag
    search_query: symfony
    api_key:      MYAPIKEY
    api_secret:   MYAPISECRET

news.templating: ~



#assets_version: SomeVersionScheme

## Twig Configuration
#twig.config:
#    auto_reload: true

## Doctrine Configuration
#doctrine.dbal:
#    dbname:   xxxxxxxx
#    user:     xxxxxxxx
#    password: ~
#doctrine.orm: ~

## Swiftmailer Configuration
#swift.mailer:
#    transport:  smtp
#    encryption: ssl
#    auth_mode:  login
#    host:       smtp.gmail.com
#    username:   xxxxxxxx
#    password:   xxxxxxxx
