#!/usr/bin/env php
<?php

require_once __DIR__.'/NewsKernel.php';

use Symfony\Bundle\FrameworkBundle\Console\Application;

$kernel = new NewsKernel('dev', true);

$application = new Application($kernel);
$application->run();
